module.exports = {
  // API routes
    confirmUserEmail: require('../routes/confirmUserEmail')
  , createNewTldr: require('../routes/createNewTldr')
  , createNewUser: require('../routes/createNewUser')
  , deleteTldr: require('../routes/deleteTldr')
  , getCreatedTldrs: require('../routes/getCreatedTldrs')
  , getLatestTldrs: require('../routes/getLatestTldrs')
  , getLoggedUser: require('../routes/getLoggedUser')
  , getTldrById: require('../routes/getTldrById')
  , getUserById: require('../routes/getUserById')
  , logout: require('../routes/logout')
  , mailchimpWebhookSync: require('../routes/mailchimpWebhookSync')
  , resendConfirmToken: require('../routes/resendConfirmToken')
  , resetPassword: require('../routes/resetPassword')
  , searchTldrs: require('../routes/searchTldrs')
  , sendResetPasswordEmail: require('../routes/sendResetPasswordEmail')
  , updateNotification: require('../routes/updateNotification')
  , updateGravatarEmail: require('../routes/updateGravatarEmail')
  , updatePassword: require('../routes/updatePassword')
  , updateProfile: require('../routes/updateProfile')
  , updateTldrWithId: require('../routes/updateTldrWithId')

  // Website routes
  , website_about: require('../routes/website/about')
  , website_account: require('../routes/website/account')
  , website_confirmEmail: require('../routes/website/confirmEmail')
  , website_forgotPassword: require('../routes/website/forgotPassword')
  , website_index: require('../routes/website/index')
  , website_notifications: require('../routes/website/notifications')
  , website_login: require('../routes/website/login')
  , website_resetPassword: require('../routes/website/resetPassword')
  , website_signup: require('../routes/website/signup')
  , website_summaries: require('../routes/website/summaries')
  , website_tldrscreated: require('../routes/website/tldrscreated')
  , website_userPublicProfile: require('../routes/website/userPublicProfile')
  , website_whatisit: require('../routes/website/whatisit')
  };
