// API routes
var routes = {
    addSubscriber: require('../routes/addSubscriber')
  , moderateTldr: require('../routes/moderateTldr')
  , allowHover: require('../routes/allowHover')
  , blockTldr: require('../routes/blockTldr')
  , confirmUserEmail: require('../routes/confirmUserEmail')
  , createNewTldr: require('../routes/createNewTldr')
  , createNewUser: require('../routes/createNewUser')
  , deleteTldr: require('../routes/deleteTldr')
  , deleteTldrIfPossible: require('../routes/deleteTldrIfPossible')
  , deleteUser: require('../routes/deleteUser')
  , getCategories: require('../routes/getCategories')
  , getCreatedTldrs: require('../routes/getCreatedTldrs')
  , getLatestTldrs: require('../routes/getLatestTldrs')
  , getLoggedUser: require('../routes/getLoggedUser')
  , getStats: require('../routes/getStats')
  , getTldrsByCategory: require('../routes/getTldrsByCategory')
  , getTldrById: require('../routes/getTldrById')
  , getUser: require('../routes/getUser')
  , incrementReadCountByBatch: require('../routes/incrementReadCountByBatch')
  , logout: require('../routes/logout')
  , mailchimpWebhookSync: require('../routes/mailchimpWebhookSync')
  , resendConfirmToken: require('../routes/resendConfirmToken')
  , resetPassword: require('../routes/resetPassword')
  , searchTldrs: require('../routes/searchTldrs')
  , searchTldrsByBatch: require('../routes/searchTldrsByBatch')
  , sendResetPasswordEmail: require('../routes/sendResetPasswordEmail')
  , shareThroughBuffer: require('../routes/shareThroughBuffer')
  , subscribeEmailAddress: require('../routes/subscribeEmailAddress')
  , thankContributor: require('../routes/thankContributor')
  , updateDistributionChannels: require('../routes/updateDistributionChannels')
  , updateGravatarEmail: require('../routes/updateGravatarEmail')
  , updatePassword: require('../routes/updatePassword')
  , updateProfile: require('../routes/updateProfile')
  , updateTldrWithId: require('../routes/updateTldrWithId')
  , voteOnThread: require('../routes/voteOnThread')
  };


// Website routes
routes.website = {
    about: require('../routes/website/about')
  , account: require('../routes/website/account')
  , addCategories: require('../routes/website/add-categories')
  , analytics: require('../routes/website/analytics')
  , apiDoc: require('../routes/website/apiDoc')
  , changePostText: require('../routes/website/changePostText')
  , browser_extension: require('../routes/website/browserExtension')
  , confirmEmail: require('../routes/website/confirmEmail')
  , discover: require('../routes/website/discover')
  , editPost: require('../routes/website/editPost')
  , elad: require('../routes/website/elad')
  , embedAdmin: require('../routes/website/embed-admin')
  , embeddedTldrs: require('../routes/website/embeddedTldrs')
  , forgotPassword: require('../routes/website/forgotPassword')
  , forum: require('../routes/website/forum')
  , forumAddPost: require('../routes/website/forumAddPost')
  , forumCreateThread: require('../routes/website/forumCreateThread')
  , forumNewThread: require('../routes/website/forumNewThread')
  , forumShowThread: require('../routes/website/forumShowThread')
  , googleSSOWithPopup: require('../routes/website/googleSSOWithPopup')
  , index: require('../routes/website/index')
  , login: require('../routes/website/login')
  , moderation: require('../routes/website/moderation')
  , pickUsername: require('../routes/website/pickUsername')
  , resetPassword: require('../routes/website/resetPassword')
  , releaseNotes: require('../routes/website/releaseNotes')
  , scratchpad: require('../routes/website/scratchpad')
  , signup: require('../routes/website/signup')
  , latestTldrs: require('../routes/website/latestTldrs')
  , tldrEmbed: require('../routes/website/tldrEmbed')
  , tldrPage: require('../routes/website/tldrPage')
  , tldrscreated: require('../routes/website/tldrscreated')
  , twitterAnalytics: require('../routes/website/twitterAnalytics')
  , unsubscribe: require('../routes/website/unsubscribe')
  , userPublicProfile: require('../routes/website/userPublicProfile')
  , whatisit: require('../routes/website/whatisit')
  };


module.exports = routes;
